// AUTO-GENERATED BY FREESAIL CLI - DO NOT EDIT
// Re-run `freesail prepare catalog` to regenerate this file.

import type { FreesailComponentProps, FunctionImplementation } from '@freesail/react';
import type React from 'react';

import { StandardCatalog } from '@freesail/standard-catalog';

export const includedComponents: Record<string, React.ComponentType<FreesailComponentProps>> = {
  Row: StandardCatalog.components['Row']!,
  Column: StandardCatalog.components['Column']!,
  Card: StandardCatalog.components['Card']!,
  Spacer: StandardCatalog.components['Spacer']!,
};

export const includedFunctions: Record<string, FunctionImplementation> = {
  formatString: StandardCatalog.functions!['formatString']!,
  formatDate: StandardCatalog.functions!['formatDate']!,
  now: StandardCatalog.functions!['now']!,
};
