/**
 * Run this script to generate the base64 logo constant:
 *   npx tsx scripts/generate-logo-base64.ts
 *
 * It reads the Thendral logo PNG and writes a TypeScript constant file
 * that can be imported directly by the SDK.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const logoPath = path.resolve(__dirname, '../packages/@freesail/react/src/img/thendralLogo.png');
const outputPath = path.resolve(__dirname, '../packages/@freesail/react/src/logo.ts');

const imageBuffer = fs.readFileSync(logoPath);
const base64 = imageBuffer.toString('base64');
const dataUri = `data:image/png;base64,${base64}`;

const content = `// Auto-generated by scripts/generate-logo-base64.ts — do not edit manually
export const FREESAIL_LOGO_DATA_URI = '${dataUri}';
`;

fs.writeFileSync(outputPath, content, 'utf-8');
console.log(`✅ Generated ${outputPath} (${base64.length} base64 chars)`);
